name: Build & Push HyperHDR Add-on Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

jobs:
  build-addon:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from config.json
        id: version
        run: |
          VERSION=$(jq -r '.version' addon-hyperhdr/config.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION}"

      - name: Build and push multi-arch Docker images
        uses: home-assistant/builder@master
        with:
          args: |
            --target addon-hyperhdr \
            --docker-user ${{ secrets.DOCKER_USERNAME }} \
            --docker-password ${{ secrets.DOCKER_PASSWORD }} \
            --all

env:
  DOCKER_BUILDKIT: 1
